### ISSUE TITLE
ML - Add more ML Models

### ISSUE THREAD

**Issue by Mohammad4844** [COSC481W-2024Fall/MLite#30]
### User Story:

As a user, I would like to have a wide range of models to choose from when inputting a dataset.

### Persona:

Stacy the data science student would like to have a wide range of models, so that she has the ability to choose a model that will best describe her data.

### Feature:

Provide a wide range of potential models for a user.

### Business Value:

Users will have a wide range of potential models to select their best fit from.

### Tasks

Building out a model zoo of models -- will likely be an ongoing set of issues, and has a handful of other requirements to boot.
Short list of models, implemented today and intending to implement:
- [x] #6 
- [x] #7 
- [ ] SVM (This sprint)
- [ ] MLP (This sprint)
- [x] #8 
- [ ] RNNs?
- [ ] LSTMs?

### Acceptance Criteria

Backend python script should output an accuracy score for MLPs and SVMs that can be used to evaluate the models' fit against others, as well as a set of model weights.

### Acceptance Tests

Run model api class and run the model functions.

**Comment by congbrian** [comment]
Building out a model zoo of models -- will likely be an ongoing set of issues, and has a handful of other requirements to boot.
Short list of models, implemented today and intending to implement:
- [x] #6 Linear Regression
- [x] #7 Logistic Regression
- [ ] SVM (This sprint)
- [ ] MLP (This sprint)
- [x] #8 Decision Trees
- [ ] RNNs?
- [ ] LSTMs?

**Comment by sjiang1** [comment]
1. please move your description to the first comment. You can edit the first comment by click the three dots ==> "edit"
